
----EXERCICIO 1------
--CREATE TABLE CLIENTES (
--ID INT IDENTITY (1,1),
--NOME VARCHAR(100) NOT NULL,
--TELEFONE NUMERIC,
--ENDERECO VARCHAR(500) NOT NULL UNIQUE);

-----EXERCICIO 2-------
--INSERT INTO CLIENTES (NOME,TELEFONE,ENDERECO) VALUES 
--('VINICIUS SILVA',987654,'Rua Girassol'),
--('Maria Antonia' ,123456 ,'Rua Rosas'),
--('Marcus Vinicius',654123,'Rua Itajai');

-------EXERCICIO 3-------
--SELECT * FROM CLIENTES;

--------EXERCICIO 4------
--SELECT * FROM CLIENTES
--WHERE ID = 3

-------EXERCICIO  5-------
--SELECT *FROM CLIENTES
--WHERE NOME LIKE '%M%'

-------EXERCICIO 6-------
--UPDATE CLIENTES
--SET ENDERECO = 'RUA DO LIMÃO'
--WHERE NOME = 'MARCUS VINICIUS'

--SELECT *FROM CLIENTES
--WHERE NOME LIKE '%M%'AND ID = 3

--------EXECICIO 7-------
--DELETE CLIENTES
--WHERE ID =2

--SELECT * FROM CLIENTES

------EXERCICIO 8--------


